"""
This type stub file was generated by pyright.
"""

from ._compat import implements_to_string

"""
This type stub file was generated by pyright.
"""
class UnexpectedUnicodeError(AssertionError, UnicodeError):
    """Raised in places where we want some better error reporting for
    unexpected unicode or binary data.
    """
    ...


@implements_to_string
class DebugFilesKeyError(KeyError, AssertionError):
    """Raised from request.files during debugging.  The idea is that it can
    provide a better error message than just a generic KeyError/BadRequest.
    """
    def __init__(self, request, key) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class FormDataRoutingRedirect(AssertionError):
    """This exception is raised by Flask in debug mode if it detects a
    redirect caused by the routing system when the request method is not
    GET, HEAD or OPTIONS.  Reasoning: form data will be dropped.
    """
    def __init__(self, request) -> None:
        ...
    


def attach_enctype_error_multidict(request):
    """Since Flask 0.8 we're monkeypatching the files object in case a
    request is detected that does not use multipart form data but the files
    object is accessed.
    """
    class newcls(oldcls):
        ...
    
    

def explain_template_loading_attempts(app, template, attempts):
    """This should help developers understand what failed"""
    ...

def explain_ignored_app_run():
    ...

